FROM debian:stable-slim AS builder

RUN apt-get update && apt-get install -y build-essential busybox-static
WORKDIR /kubemem
COPY *.c *.h Makefile ./
RUN make

FROM scratch
COPY --from=builder /kubemem/kubemem /bin/kubemem
COPY --from=builder /bin/busybox /bin/busybox

CMD ["/bin/kubemem"]
